# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-24 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lun_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lun', models.CharField(max_length=200)),
                ('all_space', models.IntegerField()),
                ('used_space', models.IntegerField()),
                ('free_space', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vm_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_name', models.CharField(max_length=200)),
                ('vm_id', models.CharField(max_length=200)),
                ('vm_cpu', models.IntegerField()),
                ('vm_mem', models.IntegerField()),
                ('vm_disk', models.IntegerField()),
                ('vm_used_space', models.IntegerField()),
                ('lun_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vm.Lun_info')),
            ],
        ),
        migrations.CreateModel(
            name='Vm_used_space_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('vm_id', models.CharField(max_length=200)),
                ('vm_used_space', models.IntegerField()),
            ],
        ),
    ]
