# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-27 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0002_auto_20180824_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='lun_info',
            name='date',
            field=models.DateTimeField(default='2018-07-08'),
        ),
    ]
