# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-27 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0006_auto_20180827_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lun_info',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
