# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-27 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0008_vm_info_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vm_info',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
