# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-29 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0009_auto_20180827_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vm_info',
            name='lun_id',
        ),
        migrations.AddField(
            model_name='vm_info',
            name='lun_id',
            field=models.ManyToManyField(to='vm.Lun_info'),
        ),
    ]
